# Site settings
name: Ruotian Zhang
title: Ruotian Zhang | Machine Learning Engineer
description: Machine learning engineer focused on image retrieval with deep learning techniques
url: https://zhangruotian.github.io/
baseurl: ''
email: zhangruotian1992@gmail.com
#cover: https://bchiang7.github.io/img/og.png
logo: https://zhangruotian.github.io/img/emojis/technologist.png
resume: https://github.com/zhangruotian/zhangruotian.github.io/blob/master/resume.pdf
social:
  - title: email
    url: mailto:zhangruotian1992@gmail.com
  - title: twitter
    url: https://twitter.com/maveric66137659
  - title: github
    url: https://github.com/zhangruotian
  - title: linkedin
    url: https://www.linkedin.com/in/ruotian-zhang

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
